= Description Operators

The description operators are

----
spec iota : pi a. (a -> prop) -> a :=
  forall (P : a -> prop).
    (exists (y : a). P y && (forall (z : a). P z => z = y)) =>
    forall (x : a). P x = (x = iota P).
----

and

----
spec eps : pi a. (a -> prop) -> a :=
  forall (P : a -> prop) (x : a). P x => P (eps P).
----

"iota" is the _definite description operator_ (Hilbert's iota). "eps" is the
_indefinite description operator_ (Hilbert's epsilon or choice). The above
specifications are (one version of their) conventional axiomatization.

"iota" returns *the* element satisfying a predicate "P" if their exists such
an element; otherwise, it returns an arbitrary element. (The arbitrary element
may be different for different predicates "P", but it must be the same for two
predicates that are equal, by congruence of equality.)

"eps" returns *an* element satisfying a predicate "P". If there exists many,
it chooses an arbitrary satisfying element (with the same twist on the word
"arbitrary" as above). If there exists none, it returns an arbitrary element.

The two operators are problematic because of the infinite quantification over
the ground type "t" that instantiates "a" (together with "spec").

Although specialization is a priori only for "rec", exceptionally "iota" and
"eps" can and should be specialized whenever possible.

For instances where "t" is finite (and not too large, e.g. <= 256), the "spec"
can (and should) be kept as such. Otherwise, the following translations should
be used (in "pseudocode"):

----
rec eps_t : H_t_prop -> t :=
  forall h. eps_t h.
    ...
----
