= Translation of Higher-Order Constructs

What are the higher-order constructs? I believe this is a complete list:

C1. Terms as formulas: x && y, where x, y : prop
C2. Formulas within terms: p (x a = x) -> p true
C3. Lambda-abstractions: (fun x y. y + x) = (+)
C4. Higher-order arguments: map f [x] = [f x]
C5. Partial function applications: f = g -> f x = g x
C6. Higher-order quantification: forall x. exists f. f x = x

C1 and C2 are not an issue for SMT-LIB or Nunchaku already today.

== Lambda-Abstractions

C3 (lambda-abstractions) can be eliminated by extensionality and by a
transformation that performs lambda-lifting (defunctionalization,
supercombinators).

=== Extensionality

Applying extensionality in this case means translating

----
lhs = rhs
----

where either lhs or rhs is a lambda-abstraction (not otherwise!) to

----
forall x. lhs x = rhs x
----

Example:

----
empty = (fun x. false)
----

to

----
forall x. empty x = false
----

=== Lambda-Lifting

Lambda-lifting introduces a new function symbol corresponding to each
lambda-abstraction. That symbol takes all the free variables (not cons of the
lambda-abstractions as argument, before taking the lambda argument itself.

Example:

----
... forall u v. P (fun x. fun y. F x y u v) ...
----

becomes

----
... forall u v. P (lifted1 u v) ...

rec lifted1 :=
  lifted1 u v = (fun x. fun y. F x y u v).
----

which by extensionality becomes

----
... forall u v. P (lifted1 u v) ...

rec lifted1 :=
  lifted1 u v x y = F x y u v.
----

A single definition ("lifted1") is sufficient for an iterated
lambda-abstraction (here "fun x. fun y. ...").

== Higher-Order Arguments and Partial Function Applications

*WARNING: The following text is very confusing.*

C4 (higher-order arguments) and C5 (partial function applications) go hand
in hand. In fact, C6 (higher-order quantification) is also a prerequisite for
C4, but we will study it in more generality below.

Specialization is a neat trick that takes care of some higher-order
quantifiers, e.g., the arguments to a "map" function. We will assume that it
has been applied already and look at the remaining higher-order arguments.

Consider the following example (substitution on de Bruijn terms):

----
rec subst : (nat -> term) -> term -> term :=
  forall rho j. subst rho (Var j) = rho j;
  forall rho t. subst rho (Lam t) = Lam (subst (bump 0 rho) t);
  forall rho t u. subst rho (App t u) = App (subst rho t) (subst rho u).

rec bump : nat -> (nat -> term) -> nat -> term :=
  forall n rho. bump rho 0 = Var n;
  forall n rho m. bump rho (Suc m) = lift (rho m).
----

=== Handles

The trick here is to replace the higher-order function arrow by a new type. We
could call it an (associative) "array" but that would be confusing because we
are not going to use the built-in SMT theory of arrays to represent them. Let
us call such new types _handle types_, and values of those types _handles_.

Each handle type "H" corresponding to the function space "T -> U" is equipped
with the following sort and operations:

----
(* the actual operations *)
val app_H : H -> T -> U.
val prototype_H : H -> T.

(* an abstraction type with two gamma projections *)
val alpha_H : type.
val gamma1_H : alpha_H -> H.
val gamma2_H : alpha_H -> T.
----

(Let's drop the "_H"s.) The intuition is as follows:

* "app" applies a handle to an argument, producing a result value. The
  function should only be applied to argument values for which a corresponding
  "alpha" exists.

* If there exists no "alpha" for a specific point, we a priori do not know what
  value the function takes at that point. However, if the handle "H" enjoys
  the property that "(H, prototype H) \in alpha", we can assume that the
  function returns "app H (prototype H)" at all such points.

We will identify "alpha" with a product type "H * T" in the following, for
notational convenience. The "alpha" type is similar to the type of the same
name in the first-order translation for the "app" function (SMT 2015).

Example 1: The function that maps 0 to 1, 1 to 2, and every other integer to 0
can be represented semantically by the function "f" below:

----
app f 0 = 1
app f 1 = 2
app f 7 = 0
prototype f = 7

alpha = {(f, 0), (f, 1), (f, 7)}
----

Example 2: The successor function on the integers can be approximated by

----
app g (-3) = 2
app g 0 = 1
app g 5 = 6
prototype g = 7

alpha = {(g, -3), (g, 0), (g, 5)}
----

=== Handle Axioms

If two handles are distinct, they must really correspond to distinct
functions. This is extensionality and can be axiomatized as follows:

----
axiom forall h : H, k : H.
  h = k || (exists x : T. APP h x ~= APP k x).
----

assuming

----
abbreviation APP h j :=
  if exists b : alpha. gamma1 b = h && gamma2 b = j then
    app h j
  else if exists b : alpha. gamma1 b = h && gamma2 b = prototype h then
    app h (prototype h)
  else
    GUARD false.
----

=== Translation

For each function symbol, we compute the minimum number of arguments it ever
occurs with and pass additional arguments using "app" in the definition. For
recursively defined functions, we require

    ~ (exists b. gamma1 b = h && gamma2 b = prototype h)
    || (forall x. exists b. gamma1 b = h && gamma2 b = x)

but drop the second conjunct if x ranges over an infinite type.

Finally, any call to a function variable needs to perform a complicated lookup
routine, and guards are necessary whenever "app" or "is_dom" is checked. For
our running example, we have:

----
val H : type.
val app : H -> nat -> term.
val prototype : H -> term.

val alpha : type.
val gamma1 : alpha -> nat.
val gamma2 : alpha -> term.

rec subst : H -> term -> term :=
  forall h j. subst h (Var j) = APP h j;
  forall h t. subst h (Lam t) = Lam (subst (bump 0 h) t);
  forall h t u. subst h (App t u) = App (subst h t) (subst h u).

rec bump : nat -> H -> H :=
  forall n h m.
    app (bump n h) m = (match m with | 0 => Var n | Suc k => lift (APP h k)).
----

When bump is later translated using the first-order translation (cf. SMT
2015), some special handling is necessary to distinguish between the actual
function application and the indirect one through "app":

----
rec bump : nat -> H -> H :=
  forall (a : alpha_bump) (b : alpha_H).
    gamma1_H b = bump (gamma1_bump a) (gamma2_bump a) ->
      app (bump (gamma1_bump a) (gamma2_bump a)) (gamma2_H b) =
        (match m with
         | 0 => Var (gamma1_bump a)
         | Suc k => lift (APP (gamma2_bump a) k)).
----

And we need one more axiom to say that "bump" has no prototype (since it is a
function introduced by "rec", with an infinite domain [alpha_bump or
alpha_H?]):

----
axiom forall (a : alpha_bump).
  let h = bump (gamma1_bump a) (gamma2_bump a) in
    forall b : alpha_H. gamma1_H b ~= h || gamma2_H b ~= prototype h.
----

=== Partially Applied Functions as Arguments to Equality

A comparison "f = g" for "f", "g" functions is problematic. After the above
translation, "f" and "g" are handles. But the same handle can correspond to
two distinct functions. For example,

----
rec bad :=
  bad 0 = (S 0);
  bad (S 0) = S (S 0);
  bad (S (S n)) = 0.
----

and

----
rec suc :=
  suc n = S n.
----

may both be approximated by the handle

----
app f 0 = 1
app f 1 = 2
app f 7 = 0
prototype f = 7

alpha = {(f, 0), (f, 1), (f, 7)}
----

This means we have to be careful when comparing handles. In negative contexts,
equalities such as "f = g" can be left as is. (Indeed, we rely implicitly on
this for the built-in equality rules, e.g. congruence.) After all, in such
contexts, it is OK to return "true" instead of "false". In positive contexts,
we need a full scale comparison like this:

*BEGIN FIXME*
----
f = g
&&
(exists a : alpha. gamma1 a = f && gamma2 a = prototype a)
----
*END FIXME*

== Higher-Order Quantification

If we are lucky, skolemization eliminates a higher-order quantifier before it
causes any trouble. Or perhaps the higher-order quantifier is in a recursive
definition, and then it becomes first-order thanks to the introduction of a
handle.

If the quantification is of the form "\forall x. f x = g x" (for some terms "f
x" and "g x" that may contain "x", it can be rewritten into "f = g", and then
the techniques for partially applied functions as arguments to equality apply.

The remaining cases are:

* _The quantification is over a finite domain (after the possible introduction
  of handles, which can transform some infinite types into finite ones)._
  E.g. "prop -> prop". This could in principle be handled using SMT arrays,
  but according to AJR arrays do not mix well with finite model finding. Maybe
  we just give up, like we do for infinite quantification (with the wrong
  polarity).

* _The quantification is over an infinite domain._ E.g. "nat -> nat".
  This is virtually hopeless.
