= Syntax of Generated Models

== Current Situation

The current output is broken in some cases. Take "bugs/rec_model.nun":

----
val a : type.

data list :=
  Nil
| Cons a list.

rec append : list -> list -> list :=
  forall (zs : list). append Nil zs = zs;
  forall (x : a) (ws : list) (zs : list). append (Cons x ws) zs = Cons x (append ws zs).

val xs : list.
val ys : list.

goal ~ (append xs ys = append ys xs).
----

Nunchaku's output is currently

----
SAT:
  (model
     (terms
        ((ys Cons @uc_a_1 Nil)
         (xs Cons @uc_a_0 Nil)
         (append
            fun ($x1:list).
              fun ($x2:list).
                if
                  (($x1
                    =
                    (if (@uc_G_append_3 = $x1)
                     then Nil
                     else
                       if (@uc_G_append_2 = $x1)
                       then Nil
                       else
                         if (@uc_G_append_1 = $x1)
                         then Cons @uc_a_1 Nil
                         else Cons @uc_a_0 Nil))
                   &&
                   ($x2
                    =
                    (if (@uc_G_append_1 = $x1)
                     then Cons @uc_a_0 Nil
                     else
                       if (@uc_G_append_3 = $x1)
                       then Cons @uc_a_0 Nil
                       else Cons @uc_a_1 Nil)))
                then Cons @uc_a_1 (Cons @uc_a_0 Nil)
                else
                  if
                    (($x1
                      =
                      (if (@uc_G_append_3 = $x1)
                       then Nil
                       else
                         if (@uc_G_append_2 = $x1)
                         then Nil
                         else
                           if (@uc_G_append_1 = $x1)
                           then Cons @uc_a_1 Nil
                           else Cons @uc_a_0 Nil))
                     &&
                     ($x2
                      =
                      (if (@uc_G_append_1 = $x1)
                       then Cons @uc_a_0 Nil
                       else
                         if (@uc_G_append_3 = $x1)
                         then Cons @uc_a_0 Nil
                         else Cons @uc_a_1 Nil)))
                  then Cons @uc_a_1 (Cons @uc_a_0 Nil)
                  else
                    if
                      (($x1
                        =
                        (if (@uc_G_append_3 = $x1)
                         then Nil
                         else
                           if (@uc_G_append_2 = $x1)
                           then Nil
                           else
                             if (@uc_G_append_1 = $x1)
                             then Cons @uc_a_1 Nil
                             else Cons @uc_a_0 Nil))
                       &&
                       ($x2
                        =
                        (if (@uc_G_append_1 = $x1)
                         then Cons @uc_a_0 Nil
                         else
                           if (@uc_G_append_3 = $x1)
                           then Cons @uc_a_0 Nil
                           else Cons @uc_a_1 Nil)))
                    then Cons @uc_a_1 (Cons @uc_a_0 Nil)
                    else
                      if
                        (($x1
                          =
                          (if (@uc_G_append_3 = $x1)
                           then Nil
                           else
                             if (@uc_G_append_2 = $x1)
                             then Nil
                             else
                               if (@uc_G_append_1 = $x1)
                               then Cons @uc_a_1 Nil
                               else Cons @uc_a_0 Nil))
                         &&
                         ($x2
                          =
                          (if (@uc_G_append_1 = $x1)
                           then Cons @uc_a_0 Nil
                           else
                             if (@uc_G_append_3 = $x1)
                             then Cons @uc_a_0 Nil
                             else Cons @uc_a_1 Nil)))
                      then Cons @uc_a_1 (Cons @uc_a_0 Nil)
                      else ?__))
     (types ((a {@uc_a_1, @uc_a_0})))
  ))
----

The symbols @uc_G_append_3 etc. have no business in there.

The model given by CVC4 looks like this:

----
(define-fun __nun_card_witness_1 () G_append @uc_G_append_0)
(define-fun append (($x1 list) ($x2 list)) list (ite (and (= $x1 (Cons @uc_a_1 (Cons @uc_a_0 (Cons @uc_a_0 Nil)))) (= $x2 (Cons @uc_a_1 Nil))) (Cons @uc_a_0 (Cons @uc_a_0 (Cons @uc_a_0 Nil))) (ite (and (= $x1 (Cons @uc_a_1 (Cons @uc_a_0 (Cons @uc_a_0 Nil)))) (= $x2 (Cons @uc_a_0 Nil))) (Cons @uc_a_2 (Cons @uc_a_0 Nil)) (ite (and (= $x1 (Cons @uc_a_1 Nil)) (= $x2 (Cons @uc_a_0 Nil))) (Cons @uc_a_1 (Cons @uc_a_0 Nil)) (ite (and (= $x1 Nil) (= $x2 (Cons @uc_a_1 Nil))) (Cons @uc_a_1 Nil) (ite (and (= $x1 Nil) (= $x2 (Cons @uc_a_0 Nil))) (Cons @uc_a_0 Nil) (Cons @uc_a_0 (Cons @uc_a_1 Nil))))))))
(define-fun proj_G_append_0 (($x1 G_append)) list (ite (= @uc_G_append_3 $x1) Nil (ite (= @uc_G_append_2 $x1) Nil (ite (= @uc_G_append_1 $x1) (Cons @uc_a_0 Nil) (Cons @uc_a_1 Nil)))))
(define-fun proj_G_append_1 (($x1 G_append)) list (ite (= @uc_G_append_1 $x1) (Cons @uc_a_1 Nil) (ite (= @uc_G_append_3 $x1) (Cons @uc_a_1 Nil) (Cons @uc_a_0 Nil))))
(define-fun ys () list (Cons @uc_a_0 Nil))
(define-fun xs () list (Cons @uc_a_1 Nil))
)
----

Once we filter out "proj_G_append_*", this is almost already a good model for
Nunchaku, except that we need to massage the "append" model so that it states
clearly for all legal arguments what the value is and "?__" otherwise. Looking
at "proj_G_append_*", we see the different legal tuples of arguments:

----
@uc_G_append_0 = (Cons @uc_a_1 Nil, Cons @uc_a_0 Nil)
@uc_G_append_1 = (Cons @uc_a_0 Nil, Cons @uc_a_1 Nil)
@uc_G_append_2 = (Nil, Cons @uc_a_0 Nil)
@uc_G_append_3 = (Nil, Cons @uc_a_1 Nil)
----

So we already know that the "append" model is going to be of the form

----
append = fun $xs : list. fun $ys : list.
  if $xs = X1 && $ys = Y1 then
    Z1
  else if $xs = X2 && $ys = Y2 then
    Z2
  else if $xs = X3 && $ys = Y3 then
    Z3
  else if $xs = X4 && $ys = Y4 then
    Z4
  else
    ?__ $xs $ys
----

Notice the arguments to "?__": They indicate the dependency of the unspecified
value on its arguments. An alternative is simply to write "append $xs $ys".
Maybe that's the clearest one. In any case, the dependencies should be clearly
marked. (One of my regrets with Nitpick is that I used the "..." notation for
lots of things, resulting in an unclear notion of partial model.)

Now we plug in the values from the "@uc_G_append_*" tuples given above for the
"Xs" and "Ys":

----
append = fun $xs : list. fun $ys : list.
  if $xs = Cons @uc_a_1 Nil && $ys = Cons @uc_a_0 Nil then
    Z1
  else if $xs = Cons @uc_a_0 Nil && $ys = Cons @uc_a_1 Nil then
    Z2
  else if $xs = Nil && $ys = Cons @uc_a_0 Nil then
    Z3
  else if $xs = Nil && $ys = Cons @uc_a_1 Nil then
    Z4
  else
    ?__ $xs $ys
----

Now we perform a lookup in the model of "append" generated by CVC4. The model
looks like this (with better indentation than above):

----
append = fun $x1 : list. fun $x2 : list.
  ite (and (= $x1 (Cons @uc_a_1 (Cons @uc_a_0 (Cons @uc_a_0 Nil)))) (= $x2 (Cons @uc_a_1 Nil)))
    (Cons @uc_a_0 (Cons @uc_a_0 (Cons @uc_a_0 Nil)))
    (ite (and (= $x1 (Cons @uc_a_1 (Cons @uc_a_0 (Cons @uc_a_0 Nil)))) (= $x2 (Cons @uc_a_0 Nil)))
      (Cons @uc_a_2 (Cons @uc_a_0 Nil))
      (ite (and (= $x1 (Cons @uc_a_1 Nil)) (= $x2 (Cons @uc_a_0 Nil)))
        (Cons @uc_a_1 (Cons @uc_a_0 Nil))
        (ite (and (= $x1 Nil) (= $x2 (Cons @uc_a_1 Nil)))
          (Cons @uc_a_1 Nil)
          (ite (and (= $x1 Nil) (= $x2 (Cons @uc_a_0 Nil)))
            (Cons @uc_a_0 Nil)
            (Cons @uc_a_0 (Cons @uc_a_1 Nil))))))))
----

Notice that the first two branches are completely superfluous -- they're pure
junk. We never look these up, so that's OK. Filling in the values, we get:

----
append = fun $xs : list. fun $ys : list.
  if $xs = Cons @uc_a_1 Nil && $ys = Cons @uc_a_0 Nil then
    Cons @uc_a_1 (Cons @uc_a_0 Nil)   (* 3rd case above *)
  else if $xs = Cons @uc_a_0 Nil && $ys = Cons @uc_a_1 Nil then
    Cons @uc_a_0 (Cons @uc_a_1 Nil)   (* 6th case above)
  else if $xs = Nil && $ys = Cons @uc_a_0 Nil then
    Cons @uc_a_0 Nil   (* 5th case above *)
  else if $xs = Nil && $ys = Cons @uc_a_1 Nil then
    Cons @uc_a_1 Nil   (* 4th case above *)
  else
    ?__ $xs $ys
----

That's it.

== General Syntax.


== Generated Names



*More to come.*
