= Nunchaku
:toc: macro
:source-highlighter: pygments

A counter-example finder for higher-order logic, designed to be used from
various proof assistants. A spiritual successor to Nitpick.

Nunchaku relies upon recent versions
of http://cvc4.cs.nyu.edu/web/[the CVC4 SMT-solver]. Currently it is
necessary to use unreleased versions of CVC4, that can be found
under "development versions" on http://cvc4.cs.nyu.edu/downloads/.

We have https://github.com/nunchaku-inria/nunchaku-problems[a set of problems]
for tests and regressions, that can also be helpful to grasp the input syntax
and see how to use the constructs of Nunchaku.

toc::[]

== Contact

There is a dedicated mailing list at nunchaku-users@lists.gforge.inria.fr
  (https://lists.gforge.inria.fr/mailman/listinfo/nunchaku-users[register]).
The https://github.com/nunchaku-inria/nunchaku/issues[issue tracker] can be
used for reporting bugs.

== Documentation

See https://nunchaku-inria.github.io/nunchaku/
and link:/docs/index.adoc[the sources]

== Build

To build Nunchaku, there are several ways.


=== Released versions

Releases can be found on https://gforge.inria.fr/projects/nunchaku .

=== Opam

The easiest way is to use http://opam.ocaml.org/[opam], the package manager for
OCaml. Once opam is installed (don't forget to run `eval `opam config env``
when you want to use opam), the following should suffice:

    opam pin add -k git nunchaku https://github.com/nunchaku-inria/nunchaku.git#master

then opam should propose to install nunchaku and its dependencies. To upgrade:

    opam update
    opam upgrade nunchaku

Note that the binary is called 'nunchaku.native' until is it installed.

=== Manually

You need to install the dependencies first, namely:

- http://projects.camlcity.org/projects/findlib.html[ocamlfind]
- https://github.com/c-cube/ocaml-containers/[containers]
- http://gallium.inria.fr/~fpottier/menhir/[menhir]
- https://github.com/c-cube/sequence[sequence]
- https://github.com/c-cube/tip-parser[tip-parser] (which requires menhir)
- https://github.com/ocaml/oasis/[oasis] (to build the development version, not releases)
- ocamlbuild (provided with OCaml ≤ 4.03)

Once you have entered the source directory, type:

    ./configure
    make

== License

Free software under the BSD license. See file 'LICENSE' for more details.

== Input/Output

Supported input formats are:

- nunchaku's own input format, ML-like (extension `.nun`)
- TPTP (very partial support, extension `.p`)
- https://github.com/tip-org/[TIP] (extension `.smt2`)

Supported solver backends:

- http://cvc4.cs.nyu.edu/web/[CVC4] (development versions, we need finite model finding)
- https://github.com/tip-org/[Paradox]
- https://github.com/emina/kodkod[Kodkod] with its "kodkodi" parser


